// All copy for the site lives here. Edit freely — the pages rebuild from this file.
// Images: drop a file at images/<slug>.jpg (e.g. images/hackathon.jpg) and it replaces the generated art.

const EVENT = {
  name: "GWA Innovation Championship",
  date: "2026-10-27T07:30:00+04:00",
  dateLabel: "Tuesday 27 October 2026",
  venue: "GEMS World Academy — Main Campus",
  schedule: [
    ["07:30", "Doors open", "Team check-in, badge collection, stand set-up."],
    ["08:15", "Opening ceremony", "Welcome, rules briefing and the Innovation Challenge reveal."],
    ["08:45", "Competitions go live", "All six arenas start at the same time."],
    ["11:00", "Mid-day checkpoint", "Judges walk the floor. Short break and refuel."],
    ["12:30", "Build freeze", "Tools down. Final submissions locked."],
    ["12:45", "Presentations & judging", "Each team presents to its judging panel."],
    ["14:15", "Innovation Expo", "Every team's work on show — open to the whole school."],
    ["15:00", "Awards ceremony", "Trophies, certificates and the champions' photo."],
  ],
  awards: [
    { tier: "1st", title: "Champion", items: ["Championship trophy", "Gold winner's certificate"], cls: "gold" },
    { tier: "2nd", title: "Runner-up", items: ["Runner-up certificate"], cls: "silver" },
    { tier: "All", title: "Every participant", items: ["Certificate of participation"], cls: "all" },
    { tier: "Judges", title: "Every judge", items: ["Certificate of recognition"], cls: "judge" },
  ],
  generalRules: [
    "Teams are registered by a teacher coach before the deadline.",
    "Each student enters one competition only.",
    "All work is created on the day unless the guide says otherwise.",
    "AI tools may be used only where a competition's guide allows it — and must be declared.",
    "Respect the arena: safety first, clean stands, kind words.",
    "Judges' decisions are final.",
  ],
  faq: [
    ["Who can take part?", "Students from the year groups listed in each competition guide, registered by a teacher coach."],
    ["How do students sign up?", "Through a teacher. Coaches register their team with the Teachers · Register button."],
    ["Can a student enter more than one competition?", "No — one competition per student, so everyone can give it their best."],
    ["What should we bring?", "Each guide has a 'What to bring' list. Water bottle and school ID for everyone."],
    ["How are winners chosen?", "Each competition has its own scoring rubric, shown in its guide. Panels of teacher judges score every team."],
    ["Who gets a certificate?", "Everyone. Champions and runners-up get winner certificates, champions also lift the trophy, every participant and every judge receives a certificate."],
  ],
};

const COMPETITIONS = [
  {
    slug: "hackathon", no: "01", name: "AI & Coding Hackathon", short: "Hackathon",
    tag: "Build software that solves a real problem — in one day.",
    hue: 190, accent: "#22e1ff", glyph: "</>",
    stats: [["Team", "2–4"], ["Years", "7–13"], ["Build", "3h 45m"], ["Pitch", "4 min"]],
    overview: "Teams receive a live challenge brief at the opening ceremony, then design, code and ship a working prototype — a web app, a chatbot, a data tool or an AI-powered helper — that tackles a problem in our school or community.",
    format: [
      ["Brief reveal", "The theme is announced at 08:15. Teams have 15 minutes to choose their problem."],
      ["Build sprint", "08:45 – 12:30. Code, test, and keep a short dev log of your decisions."],
      ["Demo", "4-minute live demo plus 2 minutes of judge questions."],
    ],
    rules: [
      "Any language or framework. Starter templates are allowed; pre-written project code is not.",
      "AI coding assistants are allowed — list every AI tool used in your README.",
      "Submit a public link (repo or live URL) before the 12:30 build freeze.",
      "School Wi-Fi only; no personal hotspots.",
    ],
    judging: [["Innovation & originality", 25], ["Technical execution", 30], ["Impact on the problem", 25], ["Demo & teamwork", 20]],
    bring: ["Charged laptop + charger", "Headphones", "Accounts ready (GitHub / Replit / Code.org)", "Extension lead (one per team)"],
    tips: ["Solve one problem well instead of five badly.", "Have a working demo by 11:30 — polish after.", "Show a real user story in your pitch."],
  },
  {
    slug: "robotics", no: "02", name: "Robotics Challenge", short: "Robotics",
    tag: "Design, build and program a robot to conquer the arena.",
    hue: 22, accent: "#ff7a2f", glyph: "⚙",
    stats: [["Team", "3–5"], ["Years", "5–12"], ["Rounds", "3"], ["Match", "2 min"]],
    overview: "Teams bring a robot built from any kit (LEGO Spike, VEX, Arduino, micro:bit) and face a timed obstacle and task arena. The field layout is published one week before; a surprise mission is revealed on the day.",
    format: [
      ["Inspection", "Robots are checked for size (max 30 × 30 × 30 cm) and safety at check-in."],
      ["Qualifying runs", "Three 2-minute runs; the best score counts."],
      ["Surprise mission", "45 minutes to re-program for a new task revealed at 11:00."],
      ["Engineering interview", "5 minutes with judges about your design journey."],
    ],
    rules: [
      "Autonomous runs score double; remote-controlled runs are allowed.",
      "Maximum 30 × 30 × 30 cm at the start of a run; 2 kg weight limit.",
      "Only team members may touch the robot during a run.",
      "Bring an engineering notebook (paper or digital) showing your iterations.",
    ],
    judging: [["Arena performance", 40], ["Surprise mission", 20], ["Engineering design", 25], ["Notebook & interview", 15]],
    bring: ["Robot + spare parts", "Laptop with programming software", "Charged batteries ×2", "Engineering notebook"],
    tips: ["Test on a printed copy of the field.", "Make your code easy to change for the surprise mission.", "Label every cable."],
  },
  {
    slug: "pitch", no: "03", name: "Young Entrepreneurs Pitch", short: "Pitch",
    tag: "Turn an idea into a venture — and convince the panel.",
    hue: 44, accent: "#ffc93c", glyph: "◆",
    stats: [["Team", "2–4"], ["Years", "8–13"], ["Pitch", "5 min"], ["Q&A", "3 min"]],
    overview: "Shark-tank style. Teams present a business or social-enterprise idea, a simple business model and a prototype or mock-up. The best ventures show a real customer, a clear value, and a team that can deliver.",
    format: [
      ["Prepare", "Arrive with your idea; refine your deck and prototype in the morning studio."],
      ["Pitch", "5 minutes on stage — slides optional, energy required."],
      ["Investor Q&A", "3 minutes of questions from the judging panel."],
    ],
    rules: [
      "Idea must be original to the team.",
      "Maximum 8 slides. Video clips up to 30 seconds.",
      "Include: problem, customer, solution, business model, costs, next step.",
      "All figures must be realistic and explained.",
    ],
    judging: [["Problem & customer insight", 20], ["Innovation of solution", 25], ["Business model & viability", 25], ["Pitch delivery & Q&A", 30]],
    bring: ["Slides on USB + cloud link", "Prototype or mock-up", "One-page summary ×3 for judges"],
    tips: ["Open with a story, not a statistic.", "Know your numbers by heart.", "Answer the question that was asked."],
  },
  {
    slug: "science", no: "04", name: "Sustainability Science Lab", short: "Science",
    tag: "Prototype a greener future with real science.",
    hue: 150, accent: "#3df2a2", glyph: "⚗",
    stats: [["Team", "2–4"], ["Years", "4–11"], ["Stand", "1 table"], ["Talk", "4 min"]],
    overview: "Teams investigate an environmental challenge — energy, water, waste, food or air — and present an experiment or working prototype at a science-fair stand, backed by data they collected.",
    format: [
      ["Stand set-up", "07:30 – 08:45. One table and one power socket per team."],
      ["Live demo window", "Judges visit stands between 09:00 and 12:30."],
      ["Panel talk", "4-minute talk and questions at your stand."],
    ],
    rules: [
      "Follow the scientific method: question, hypothesis, method, results, conclusion.",
      "No open flames, hazardous chemicals or live animals.",
      "Data must be your own; sources must be cited.",
      "Display board max A1 size.",
    ],
    judging: [["Scientific method", 30], ["Sustainability impact", 25], ["Creativity of solution", 25], ["Communication", 20]],
    bring: ["Prototype / experiment", "A1 display board", "Lab notebook with raw data", "Safety equipment if needed"],
    tips: ["Show your failed attempts — judges love iteration.", "Graphs over walls of text.", "Explain who benefits and how much."],
  },
  {
    slug: "gamedesign", no: "05", name: "Game & App Design", short: "Game & App",
    tag: "Design the next game or app everyone wants to play.",
    hue: 300, accent: "#ff4fd8", glyph: "▶",
    stats: [["Team", "1–3"], ["Years", "6–13"], ["Build", "3h 45m"], ["Play-test", "Live"]],
    overview: "Create a playable game or interactive app prototype around the theme announced on the day. Scratch, Roblox Studio, Unity, Godot, Figma or any tool you love — judges play what you make.",
    format: [
      ["Theme reveal", "Announced at the opening ceremony."],
      ["Design & build", "08:45 – 12:30, including a play-test with another team at 11:00."],
      ["Showcase", "Judges and visitors play your game at the Expo."],
    ],
    rules: [
      "Game must clearly connect to the theme.",
      "Free, credited assets allowed; core mechanics must be built on the day.",
      "Content must be suitable for all ages.",
      "Submit a playable build or share link before 12:30.",
    ],
    judging: [["Fun & gameplay", 30], ["Creativity & theme", 25], ["User experience & design", 25], ["Technical polish", 20]],
    bring: ["Laptop + mouse", "Headphones", "Installed engine / tool", "Sketchbook for ideas"],
    tips: ["Find the fun in the first hour.", "Make the first 30 seconds unforgettable.", "Watch someone play — don't explain."],
  },
  {
    slug: "media", no: "06", name: "Creative Media & Film", short: "Media",
    tag: "Tell an innovation story through film, animation or design.",
    hue: 8, accent: "#ff5d6c", glyph: "◉",
    stats: [["Team", "2–4"], ["Years", "3–13"], ["Film", "≤ 90 s"], ["Edit", "On site"]],
    overview: "Teams script, shoot and edit a short film, animation or motion-graphics piece that shows how innovation can change our world. Films are screened at the awards ceremony.",
    format: [
      ["Storyboard", "08:45 – 09:30. Judges sign off your storyboard."],
      ["Shoot & edit", "09:30 – 12:30 anywhere in the designated campus zones."],
      ["Premiere", "Shortlisted films screen before the awards."],
    ],
    rules: [
      "Maximum 90 seconds including credits.",
      "All footage shot on the day; royalty-free music only.",
      "Every person on camera must agree to be filmed.",
      "Export MP4 1080p and upload before 12:30.",
    ],
    judging: [["Story & message", 30], ["Creativity & style", 25], ["Technical quality", 25], ["Use of the theme", 20]],
    bring: ["Phone / camera + charger", "Editing app installed (CapCut / iMovie / Premiere)", "Tripod or gimbal", "Headphones"],
    tips: ["Plan every shot before you film.", "Good sound beats good picture.", "Cut ruthlessly — short is strong."],
  },
];
